### ISSUE TITLE
リンク先にミス？

### ISSUE THREAD

**Issue by taisukef** [Sports-day/.github#1]
> https://github.com/Sports-day/.github/blob/main/profile/README.md?plain=1#L62

[infra](https://github.com/Sports-day/infra) </br>

→ [infra](https://github.com/Sports-day/infra-docker-procon) </br>

**Comment by testusuke** [comment]
issueありがとうございます！

諸都合で一定期間Privateにしておりました🙏
Publicにしておきましたのでご覧ください〜！
